import React, {useEffect, useMemo, useRef, useState} from 'react';
import {ArrowDown, ArrowLeft, ArrowUp, Check, ChevronRight, Copy, Download, FileJson, FilePlus2, FileText, GripVertical, ListTree, Plus, Printer, Redo2, RotateCcw, Save, Search, Trash2, Undo2, X} from 'lucide-react';
import {createBlock, createDocument, DocumentBlock, DocumentBlockType, DocumentComment, migrateDocument, StudioDocument, templates} from './templates';

const STORAGE_KEY='autocubes-documents-v2';
const LEGACY_KEY='autocubes-documents-v1';
const INDEX_KEY='autocubes-documents-index';
const blockTypes:DocumentBlockType[]=['text','checklist','table','callout','quote','deliverables','timeline','budget','approval','signature','image','pageBreak'];
const blockLabels:Record<DocumentBlockType,string>={text:'Text',checklist:'Checklist',table:'Table',callout:'Callout',quote:'Quote',deliverables:'Deliverables',timeline:'Timeline',budget:'Budget',approval:'Approval',signature:'Signature',image:'Image',pageBreak:'Page break'};
const escapeHTML=(value:string)=>value.replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]!));
const paragraphs=(value:string)=>value.split(/\n+/).filter(Boolean).map((line)=>`<p>${escapeHTML(line)}</p>`).join('');

const loadDocuments=():StudioDocument[]=>{
  try {const stored=JSON.parse(localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_KEY)||'[]') as StudioDocument[];return stored.map(migrateDocument);} catch{return [];}
};

const renderBlockHtml=(block:DocumentBlock)=>{
  if(block.type==='pageBreak') return '<div class="page-break"></div>';
  if(block.type==='image') return `<section><h2>${escapeHTML(block.heading)}</h2>${block.url?`<img src="${escapeHTML(block.url)}" alt="${escapeHTML(block.caption??'')}">`:''}<p>${escapeHTML(block.caption??block.body)}</p></section>`;
  if(block.type==='checklist'||block.type==='deliverables'||block.type==='timeline') return `<section class="block-${block.type}"><h2>${escapeHTML(block.heading)}</h2>${paragraphs(block.body)}<ul>${(block.items??[]).map((item,index)=>`<li>${block.type==='checklist'?`<span>${block.checked?.[index]?'✓':'□'}</span>`:''}${escapeHTML(item)}</li>`).join('')}</ul></section>`;
  if(block.type==='table'||block.type==='budget') return `<section><h2>${escapeHTML(block.heading)}</h2>${paragraphs(block.body)}<table>${(block.rows??[]).map((row,index)=>`<tr>${row.map((cell)=>`<${index?'td':'th'}>${escapeHTML(cell)}</${index?'td':'th'}>`).join('')}</tr>`).join('')}</table></section>`;
  return `<section class="block-${block.type}"><h2>${escapeHTML(block.heading)}</h2>${paragraphs(block.body)}</section>`;
};

const documentHtml=(document:StudioDocument)=>`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHTML(document.title)}</title><style>*{box-sizing:border-box}body{margin:0;color:#171713;background:#fff;font:15px/1.65 Arial,sans-serif}.doc{max-width:800px;margin:auto;padding:54px 42px 70px}.head,.foot{display:flex;justify-content:space-between;align-items:center;padding-bottom:20px;border-bottom:1px solid #171713}.brand{font-weight:700;letter-spacing:.08em}.meta{color:#68685f;font-size:11px}h1{margin:38px 0 14px;font-size:31px;line-height:1.16}h2{margin:38px 0 12px;font-size:18px}p{margin:0 0 12px}.intro{font-size:17px}.client{margin:22px 0 0;padding:13px 0;border-top:1px solid #ddd;border-bottom:1px solid #ddd;color:#555;font-size:12px}ul{padding-left:20px}li{margin:7px 0}table{width:100%;border-collapse:collapse}th,td{padding:8px;border:1px solid #ddd;text-align:left;font-size:12px}.block-callout,.block-approval{padding:16px;border-left:4px solid ${document.accent??'#ff5a2f'};background:#f4f4f0}.block-quote{padding-left:20px;border-left:1px solid #222;font-size:19px}.foot{margin-top:60px;padding-top:14px;padding-bottom:0;border-top:1px solid #ddd;border-bottom:0;color:#777;font-size:11px}img{max-width:100%}.page-break{break-before:page}@media(max-width:600px){.doc{padding:28px 20px}}@media print{.doc{max-width:none;padding:0}@page{margin:18mm}}</style></head><body><main class="doc"><header class="head"><div class="brand">AUTOCUBES</div><div class="meta">${escapeHTML(document.type)} · ${escapeHTML(document.date)}</div></header><h1>${escapeHTML(document.title)}</h1><p class="intro">${escapeHTML(document.intro)}</p><div class="client">${escapeHTML(document.client)} · ${escapeHTML(document.project)} · ${escapeHTML(document.status)}</div>${document.blocks.map(renderBlockHtml).join('')}<footer class="foot"><span>autocubes.site</span><span>${escapeHTML(document.status)}</span></footer></main></body></html>`;

const documentMarkdown=(document:StudioDocument)=>`# ${document.title}\n\n${document.intro}\n\n**Client:** ${document.client}  \n**Project:** ${document.project}  \n**Status:** ${document.status}\n\n${document.blocks.map((block)=>block.type==='pageBreak'?'---':`## ${block.heading}\n\n${block.body}${block.items?.length?`\n\n${block.items.map((item,index)=>`${block.type==='checklist'?(block.checked?.[index]?'[x]':'[ ]'):'-'} ${item}`).join('\n')}`:''}${block.rows?.length?`\n\n${block.rows.map((row)=>`| ${row.join(' | ')} |`).join('\n')}`:''}`).join('\n\n')}\n`;

const downloadText=(name:string,type:string,content:string)=>{const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);};

export const DocumentsApp=()=>{
  const query=useMemo(()=>new URLSearchParams(location.search),[]);
  const [documents,setDocuments]=useState<StudioDocument[]>(()=>{const stored=loadDocuments();return stored.length?stored:[createDocument(query.get('new')||'creative-brief')];});
  const [currentId,setCurrentId]=useState(()=>query.get('id')||documents[0].id);
  const [selectedBlockId,setSelectedBlockId]=useState<string>();
  const [showTemplates,setShowTemplates]=useState(false);
  const [showBlockMenu,setShowBlockMenu]=useState(false);
  const [search,setSearch]=useState('');
  const [notice,setNotice]=useState('');
  const history=useRef<StudioDocument[]>([]);
  const future=useRef<StudioDocument[]>([]);
  const current=documents.find((document)=>document.id===currentId)??documents[0];
  const selectedBlock=current.blocks.find((block)=>block.id===selectedBlockId);

  useEffect(()=>{localStorage.setItem(STORAGE_KEY,JSON.stringify(documents));localStorage.setItem(INDEX_KEY,JSON.stringify(documents.map(({id,title,type,updatedAt,client,project,status})=>({id,title,type,updatedAt,client,project,status}))));},[documents]);
  useEffect(()=>{if(!notice)return;const timer=window.setTimeout(()=>setNotice(''),1800);return()=>window.clearTimeout(timer);},[notice]);

  const replaceCurrent=(next:StudioDocument,record=true)=>{if(record){history.current.push(structuredClone(current));history.current=history.current.slice(-60);future.current=[];}setDocuments((items)=>items.map((document)=>document.id===current.id?{...next,updatedAt:new Date().toISOString()}:document));};
  const update=(patch:Partial<StudioDocument>)=>replaceCurrent({...current,...patch});
  const updateBlock=(id:string,patch:Partial<DocumentBlock>)=>replaceCurrent({...current,blocks:current.blocks.map((block)=>block.id===id?{...block,...patch}:block)});
  const undo=()=>{const previous=history.current.pop();if(!previous)return;future.current.push(structuredClone(current));replaceCurrent(previous,false);};
  const redo=()=>{const next=future.current.pop();if(!next)return;history.current.push(structuredClone(current));replaceCurrent(next,false);};

  useEffect(()=>{const key=(event:KeyboardEvent)=>{const field=event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();setNotice('Saved locally');}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'&&!event.shiftKey){event.preventDefault();undo();}if((event.ctrlKey||event.metaKey)&&(event.key.toLowerCase()==='y'||event.shiftKey&&event.key.toLowerCase()==='z')){event.preventDefault();redo();}if(!field&&event.key==='/'){event.preventDefault();setShowBlockMenu(true);}if(event.key==='Escape'){setShowBlockMenu(false);setShowTemplates(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});

  const moveBlock=(id:string,direction:-1|1)=>{const blocks=[...current.blocks];const index=blocks.findIndex((block)=>block.id===id);const target=index+direction;if(target<0||target>=blocks.length)return;[blocks[index],blocks[target]]=[blocks[target],blocks[index]];update({blocks});};
  const addBlock=(type:DocumentBlockType)=>{const next=createBlock(type);const selectedIndex=current.blocks.findIndex((block)=>block.id===selectedBlockId);const blocks=[...current.blocks];blocks.splice(selectedIndex<0?blocks.length:selectedIndex+1,0,next);update({blocks});setSelectedBlockId(next.id);setShowBlockMenu(false);};
  const duplicateBlock=(id:string)=>{const source=current.blocks.find((block)=>block.id===id);if(!source)return;const copy={...structuredClone(source),id:`block-${Date.now()}`};const index=current.blocks.findIndex((block)=>block.id===id);const blocks=[...current.blocks];blocks.splice(index+1,0,copy);update({blocks});setSelectedBlockId(copy.id);};
  const removeBlock=(id:string)=>{update({blocks:current.blocks.filter((block)=>block.id!==id)});setSelectedBlockId(undefined);};
  const addDocument=(templateId:string)=>{const document=createDocument(templateId);setDocuments((items)=>[...items,document]);setCurrentId(document.id);setSelectedBlockId(undefined);setShowTemplates(false);};
  const removeDocument=()=>{if(documents.length===1)return;const remaining=documents.filter((document)=>document.id!==current.id);setDocuments(remaining);setCurrentId(remaining[0].id);};
  const createVersion=()=>{const snapshot=JSON.stringify({...current,versions:[]});const versions=[...(current.versions??[]),{id:`version-${Date.now()}`,createdAt:new Date().toISOString(),label:`${current.status} · ${(current.versions?.length??0)+1}`,snapshot}];update({versions});setNotice('Version snapshot created');};
  const restoreVersion=(snapshot:string)=>{replaceCurrent({...migrateDocument(JSON.parse(snapshot) as StudioDocument),id:current.id,versions:current.versions});setNotice('Version restored');};

  const filtered=documents.filter((document)=>`${document.title} ${document.client} ${document.project}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="documents-app">
    <aside className="documents-sidebar">
      <a href="/" className="documents-brand"><ArrowLeft size={15}/><img src="/assets/brand/autocubes.svg" alt=""/><span>Documents</span></a>
      <button className="new-document" onClick={()=>setShowTemplates(true)}><FilePlus2 size={16}/>New document</button>
      <label className="document-search"><Search size={13}/><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Find document"/></label>
      <div className="document-list"><span className="side-caption">Documents · {filtered.length}</span>{filtered.map((document)=><button className={document.id===current.id?'active':''} key={document.id} onClick={()=>{setCurrentId(document.id);setSelectedBlockId(undefined);}}><span className="file-icon">{document.templateId.slice(0,1).toUpperCase()}</span><span><strong>{document.title}</strong><small>{document.client} · {document.status}</small></span></button>)}</div>
      <div className="document-side-status"><span>Local-first workspace</span><b>{documents.length} files</b></div>
    </aside>

    <main className="document-workspace">
      <header className="document-toolbar"><div><span>{current.type}</span><b>{current.status}</b></div><div className="document-history"><button onClick={undo} disabled={!history.current.length} title="Undo"><Undo2 size={15}/></button><button onClick={redo} disabled={!future.current.length} title="Redo"><Redo2 size={15}/></button></div><div><button onClick={createVersion} title="Create version snapshot"><RotateCcw size={15}/></button><button onClick={()=>window.print()} title="Print or save PDF"><Printer size={16}/></button><button onClick={()=>downloadText(`${current.templateId}.md`,'text/markdown',documentMarkdown(current))} title="Download Markdown"><FileText size={15}/></button><button onClick={()=>downloadText(`${current.templateId}.json`,'application/json',JSON.stringify(current,null,2))} title="Download JSON"><FileJson size={15}/></button><button onClick={()=>downloadText(`${current.templateId}.html`,'text/html',documentHtml(current))} title="Download standalone HTML"><Download size={16}/></button><button className="save-state"><Save size={15}/>Saved locally</button></div></header>
      <div className="paper-stage"><article className="document-paper">
        <header className="paper-head"><div className="paper-brand"><img src="/assets/brand/autocubes.svg" alt=""/><b>autocubes</b></div><div className="paper-meta">{current.type} · {current.date}</div></header>
        <input className="paper-title" value={current.title} onChange={(event)=>update({title:event.target.value})}/>
        <textarea className="paper-intro" value={current.intro} onChange={(event)=>update({intro:event.target.value})}/>
        <div className="paper-client"><input value={current.client} onChange={(event)=>update({client:event.target.value})}/><span>·</span><input value={current.project} onChange={(event)=>update({project:event.target.value})}/><span>·</span><input value={current.status} onChange={(event)=>update({status:event.target.value})}/></div>
        <div className="paper-sections">{current.blocks.map((block,index)=><BlockEditor key={block.id} block={block} selected={block.id===selectedBlockId} onSelect={()=>setSelectedBlockId(block.id)} onUpdate={(patch)=>updateBlock(block.id,patch)} onMove={(direction)=>moveBlock(block.id,direction)} onDuplicate={()=>duplicateBlock(block.id)} onRemove={()=>removeBlock(block.id)} first={index===0} last={index===current.blocks.length-1}/>)}</div>
        <div className="add-block-wrap"><button className="add-section" onClick={()=>setShowBlockMenu((value)=>!value)}><Plus size={14}/>Add block <kbd>/</kbd></button>{showBlockMenu?<BlockMenu onAdd={addBlock}/>:null}</div>
        <footer className="paper-foot"><span>autocubes.site</span><span>{current.status}</span></footer>
      </article></div>
    </main>

    <aside className="document-inspector"><div className="inspector-head"><span>{selectedBlock?'Block':'Document'}</span><button onClick={removeDocument} disabled={documents.length===1}><Trash2 size={14}/></button></div>{selectedBlock?<><label>Block type<select value={selectedBlock.type} onChange={(event)=>updateBlock(selectedBlock.id,{type:event.target.value as DocumentBlockType})}>{blockTypes.map((type)=><option key={type} value={type}>{blockLabels[type]}</option>)}</select></label><label>Heading<input value={selectedBlock.heading} onChange={(event)=>updateBlock(selectedBlock.id,{heading:event.target.value})}/></label><div className="inspector-actions-row"><button onClick={()=>duplicateBlock(selectedBlock.id)}><Copy size={13}/>Duplicate</button><button onClick={()=>removeBlock(selectedBlock.id)}><Trash2 size={13}/>Delete</button></div></>:<><label>Client<input value={current.client} onChange={(event)=>update({client:event.target.value})}/></label><label>Project<input value={current.project} onChange={(event)=>update({project:event.target.value})}/></label><label>Project ID<input value={current.projectId??''} onChange={(event)=>update({projectId:event.target.value})} placeholder="Shared Studio project"/></label><label>Date<input type="date" value={current.date} onChange={(event)=>update({date:event.target.value})}/></label><label>Status<select value={current.status} onChange={(event)=>update({status:event.target.value})}><option>Draft</option><option>Review</option><option>Approved</option><option>Archived</option></select></label><label>Accent<input type="color" value={current.accent??'#ff5a2f'} onChange={(event)=>update({accent:event.target.value})}/></label><section className="document-outline"><span><ListTree size={13}/>Outline</span>{current.blocks.map((block,index)=><button key={block.id} onClick={()=>setSelectedBlockId(block.id)}><b>{String(index+1).padStart(2,'0')}</b>{block.heading||blockLabels[block.type]}<ChevronRight size={11}/></button>)}</section><section className="version-list"><span>Versions</span>{[...(current.versions??[])].reverse().map((version)=><button key={version.id} onClick={()=>restoreVersion(version.snapshot)}><strong>{version.label}</strong><small>{new Date(version.createdAt).toLocaleString()}</small></button>)}</section></>}<CommentPanel comments={current.comments??[]} blockId={selectedBlock?.id} onChange={(comments)=>update({comments})}/></aside>
    {notice?<div className="document-toast"><Check size={14}/>{notice}</div>:null}
    {showTemplates?<div className="template-overlay" onMouseDown={(event)=>event.target===event.currentTarget&&setShowTemplates(false)}><div className="template-picker"><div className="picker-head"><div><span className="side-caption">New document</span><h2>Choose a studio template</h2></div><button onClick={()=>setShowTemplates(false)}><X size={18}/></button></div><div className="template-grid">{templates.map((template)=><button key={template.templateId} onClick={()=>addDocument(template.templateId)}><span>{template.short}</span><small>{template.category}</small><strong>{template.name}</strong><em>{template.blocks.length} blocks</em></button>)}</div></div></div>:null}
  </div>;
};

const BlockMenu=({onAdd}:{onAdd:(type:DocumentBlockType)=>void})=><div className="block-menu"><span>Insert block</span>{blockTypes.map((type)=><button key={type} onClick={()=>onAdd(type)}><Plus size={12}/>{blockLabels[type]}</button>)}</div>;

const BlockEditor=({block,selected,onSelect,onUpdate,onMove,onDuplicate,onRemove,first,last}:{block:DocumentBlock;selected:boolean;onSelect:()=>void;onUpdate:(patch:Partial<DocumentBlock>)=>void;onMove:(direction:-1|1)=>void;onDuplicate:()=>void;onRemove:()=>void;first:boolean;last:boolean})=>{
  if(block.type==='pageBreak') return <section className={`paper-block page-break-block ${selected?'selected':''}`} onClick={onSelect}><span>Page break</span><BlockControls first={first} last={last} onMove={onMove} onDuplicate={onDuplicate} onRemove={onRemove}/></section>;
  const updateItem=(index:number,value:string)=>onUpdate({items:(block.items??[]).map((item,itemIndex)=>itemIndex===index?value:item)});
  return <section className={`paper-block block-${block.type} ${selected?'selected':''}`} onClick={onSelect}>
    <BlockControls first={first} last={last} onMove={onMove} onDuplicate={onDuplicate} onRemove={onRemove}/>
    <input className="block-heading" value={block.heading} onChange={(event)=>onUpdate({heading:event.target.value})}/>
    {block.type==='image'?<><input className="block-url" value={block.url??''} onChange={(event)=>onUpdate({url:event.target.value})} placeholder="Image URL"/>{block.url?<img className="block-image" src={block.url} alt=""/>:null}<input className="block-caption" value={block.caption??''} onChange={(event)=>onUpdate({caption:event.target.value})} placeholder="Caption or alt text"/></>:null}
    {!['checklist','deliverables','timeline','table','budget','image'].includes(block.type)?<textarea value={block.body} onChange={(event)=>onUpdate({body:event.target.value})} placeholder="Write the content…"/>:null}
    {['checklist','deliverables','timeline'].includes(block.type)?<div className="block-items">{(block.items??[]).map((item,index)=><div key={index}>{block.type==='checklist'?<input type="checkbox" checked={block.checked?.[index]??false} onChange={(event)=>{const checked=[...(block.checked??[])];checked[index]=event.target.checked;onUpdate({checked});}}/>:<span>{String(index+1).padStart(2,'0')}</span>}<input value={item} onChange={(event)=>updateItem(index,event.target.value)}/><button onClick={()=>onUpdate({items:(block.items??[]).filter((_,itemIndex)=>itemIndex!==index)})}>×</button></div>)}<button onClick={()=>onUpdate({items:[...(block.items??[]),'New item'],checked:block.type==='checklist'?[...(block.checked??[]),false]:block.checked})}><Plus size={12}/>Add item</button></div>:null}
    {['table','budget'].includes(block.type)?<div className="block-table">{(block.rows??[]).map((row,rowIndex)=><div key={rowIndex} style={{gridTemplateColumns:`repeat(${row.length},minmax(90px,1fr)) auto`}}>{row.map((cell,columnIndex)=><input key={columnIndex} value={cell} onChange={(event)=>{const rows=structuredClone(block.rows??[]);rows[rowIndex][columnIndex]=event.target.value;onUpdate({rows});}}/>)}<button onClick={()=>onUpdate({rows:(block.rows??[]).filter((_,index)=>index!==rowIndex)})}>×</button></div>)}<button onClick={()=>onUpdate({rows:[...(block.rows??[]),Array.from({length:block.rows?.[0]?.length??3},()=> '')]})}><Plus size={12}/>Add row</button></div>:null}
  </section>;
};

const BlockControls=({first,last,onMove,onDuplicate,onRemove}:{first:boolean;last:boolean;onMove:(direction:-1|1)=>void;onDuplicate:()=>void;onRemove:()=>void})=><div className="section-controls"><GripVertical size={13}/><button disabled={first} onClick={()=>onMove(-1)}><ArrowUp size={12}/></button><button disabled={last} onClick={()=>onMove(1)}><ArrowDown size={12}/></button><button onClick={onDuplicate}><Copy size={12}/></button><button onClick={onRemove}><Trash2 size={12}/></button></div>;

const CommentPanel=({comments,blockId,onChange}:{comments:DocumentComment[];blockId?:string;onChange:(comments:DocumentComment[])=>void})=>{const[draft,setDraft]=useState('');const relevant=comments.filter((comment)=>!comment.blockId||comment.blockId===blockId);return <section className="comment-panel"><span>Review notes · {relevant.filter((comment)=>!comment.resolved).length}</span><div>{relevant.map((comment)=><article className={comment.resolved?'resolved':''} key={comment.id}><p>{comment.body}</p><button onClick={()=>onChange(comments.map((item)=>item.id===comment.id?{...item,resolved:!item.resolved}:item))}>{comment.resolved?'Reopen':'Resolve'}</button></article>)}</div><textarea value={draft} onChange={(event)=>setDraft(event.target.value)} placeholder={blockId?'Comment on selected block':'Document review note'}/><button disabled={!draft.trim()} onClick={()=>{onChange([...comments,{id:`comment-${Date.now()}`,blockId,body:draft.trim(),resolved:false,createdAt:new Date().toISOString()}]);setDraft('');}}>Add review note</button></section>;};
